name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: SwiftLint
      uses: raphaelbussa/swiftlint-action@main
      with:
        subcommand: lint --strict # Pass any subcommand needed
